site_name: Homelab Documentation
site_url: https://rademakr.github.io/homelab-docs/
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: blue grey
      accent: pink
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: blue grey
      accent: amber
  icon:
    annotation: material/plus-circle

plugins:
  - social
  - search

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/rademakr
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/orademakers/

nav:
  - Home: https://rademakr.github.io/" target="_blank
  - MkDocs:
        - 'Start Here': index.md
  - Nextcloud:
        - 'Setup': Nextcloud.md
  - Raspberry Pi:
        - 'RPi stuff' : RPi.md
  - Ansible:
        - 'Ansible': Ansible.md
  - TODO:
        - 'Build or document': TODO.md
  - CV:
        - 'My CV': CV-O.Rademakers_2024.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.twemoji

copyright: |
  &copy; 2025 <a href="https://github.com/rademakr"  target="_blank" rel="noopener">Olivier Rademakers</a>
